//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDiem
    {
        public int BaoCaoID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> HocKyID { get; set; }
        public Nullable<int> LopID { get; set; }
        public Nullable<int> NienKhoaID { get; set; }
        public string NoiDung { get; set; }
        public string LoaiBaoCao { get; set; }
        public System.DateTime NgayCongBo { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual NienKhoa NienKhoa { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
