//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HTQLDiemRenLuyenSinhVienEntities : DbContext
    {
        public DB_HTQLDiemRenLuyenSinhVienEntities()
            : base("name=DB_HTQLDiemRenLuyenSinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoDiem> BaoCaoDiems { get; set; }
        public virtual DbSet<DiemRenLuyen> DiemRenLuyens { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<KetQuaRenLuyen> KetQuaRenLuyens { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LichSuTrangThai> LichSuTrangThais { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<NienKhoa> NienKhoas { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomTieuChi> NhomTieuChis { get; set; }
        public virtual DbSet<PhieuDanhGia> PhieuDanhGias { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TieuChi> TieuChis { get; set; }
        public virtual DbSet<ThongKe> ThongKes { get; set; }
        public virtual DbSet<Truong> Truongs { get; set; }
    }
}
