//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaRenLuyen
    {
        public int KetQuaID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> HocKyID { get; set; }
        public int TongDiem { get; set; }
        public string XepLoai { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
