//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int NguoiDungID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
