//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDanhGia
    {
        public int PhieuDanhGiaID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> HocKyID { get; set; }
        public Nullable<int> TieuChiID { get; set; }
        public string NguonDanhGia { get; set; }
        public int Diem { get; set; }
        public string MinhChung { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        public virtual TieuChi TieuChi { get; set; }
    }
}
