//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQL_DiemRenLuyenSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public int ThongKeID { get; set; }
        public Nullable<int> HocKyID { get; set; }
        public string LoaiThongKe { get; set; }
        public string DieuKienThongKe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayThongKe { get; set; }
    
        public virtual HocKy HocKy { get; set; }
    }
}
